foreground #E3FFFF
background #1D1D22

selection_foreground #1D1D22
selection_background #E3FFFF

cursor #B0FFFE
cursor_text_color #1D1D22

active_border_color #CED0DF
inactive_border_color #91ADAC

url_color #47A895

color0 #434449
color1 #3D6A6E
color2 #817082
color3 #EE496B
color4 #47A895
color5 #CED0DF
color6 #B0FFFE
color7 #CFF7F6
color8 #91ADAC
color9 #3D6A6E
color10 #817082
color11 #EE496B
color12 #47A895
color13 #CED0DF
color14 #B0FFFE
color15 #CFF7F6