$background = rgba({{ background | default("#000000") | replace("#", "") }}ff)
$foreground = rgba({{ foreground | default("#ffffff") | replace("#", "") }}ff)

$color0 = rgba({{ color0 | default("#000000") | replace("#", "") }}ff)
$color1 = rgba({{ color1 | default("#000000") | replace("#", "") }}ff)
$color2 = rgba({{ color2 | default("#000000") | replace("#", "") }}ff)
$color3 = rgba({{ color3 | default("#000000") | replace("#", "") }}ff)
$color4 = rgba({{ color4 | default("#000000") | replace("#", "") }}ff)
$color5 = rgba({{ color5 | default("#000000") | replace("#", "") }}ff)
$color6 = rgba({{ color6 | default("#000000") | replace("#", "") }}ff)
$color7 = rgba({{ color7 | default("#000000") | replace("#", "") }}ff)
$color8 = rgba({{ color8 | default("#000000") | replace("#", "") }}ff)
$color9 = rgba({{ color9 | default("#000000") | replace("#", "") }}ff)
$color10 = rgba({{ color10 | default("#000000") | replace("#", "") }}ff)
$color11 = rgba({{ color11 | default("#000000") | replace("#", "") }}ff)
$color12 = rgba({{ color12 | default("#000000") | replace("#", "") }}ff)
$color13 = rgba({{ color13 | default("#000000") | replace("#", "") }}ff)
$color14 = rgba({{ color14 | default("#000000") | replace("#", "") }}ff)
$color15 = rgba({{ color15 | default("#000000") | replace("#", "") }}ff)