$background = rgba(292C2Dff)
$foreground = rgba(FCFACAff)

$color0 = rgba(4E5152ff)
$color1 = rgba(616F43ff)
$color2 = rgba(3B808Eff)
$color3 = rgba(B06090ff)
$color4 = rgba(F25749ff)
$color5 = rgba(B2A79Dff)
$color6 = rgba(F7F168ff)
$color7 = rgba(F3F0ABff)
$color8 = rgba(AAA878ff)
$color9 = rgba(616F43ff)
$color10 = rgba(3B808Eff)
$color11 = rgba(B06090ff)
$color12 = rgba(F25749ff)
$color13 = rgba(B2A79Dff)
$color14 = rgba(F7F168ff)
$color15 = rgba(F3F0ABff)